[package]
name = "coalesced_base"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.219", optional = true }

[dev-dependencies]
coalesced = { path = "../" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
