[package]
name = "coalesced_base"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true

[features]
serde = ["dep:serde"]
clap = ["dep:clap"]

[dependencies]
clap = { version = "4.5.32", optional = true }
serde = { version = "1.0.219", optional = true }

[dev-dependencies]
clap = { version = "4.5.32", features = ["derive"] }
coalesced = { path = "../", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
