[package]
name = "coalesced"
version = "0.1.0"
description = "Coalesced supports reading configs from multiple sources"
authors = ["hayas1 <h4ystack@gmail.com>"]
edition = "2021"

[features]
serde = ["dep:serde"]
clap = ["dep:clap"]

[dependencies]
clap = { version = "4.5.31", optional = true }
serde = { version = "1.0.218", optional = true }

[dev-dependencies]
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
