[workspace.package]
version = "0.3.2"
description = "Useful semigroup trait"
authors = ["hayas1 <h4ystack@gmail.com>"]
edition = "2024"
repository = "https://github.com/hayas1/semigroup"
license-file = "LICENSE"
readme = "README.md"

[workspace]
members = ["semigroup", "semigroup_derive"]
